# Header
menu:
  Home: https://lidong.me
  Blog: /
  Archives: /archives
  Notes: https://lidong.me/notes/
  OldBlog: https://blog.lidong.me
rss: /blog/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: bottom
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
